//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ateliware.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ateliware_favorite
    {
        public int ateliware_favorite_id { get; set; }
        public int id { get; set; }
        public string nome { get; set; }
        public string language { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
